backend:
  name: git-gateway
  branch: main  # veya default kullandığın branch adı
identity:
  enabled: true

media_folder: "static/images/uploads"   # Upload edilen resimler burada tutulur
public_folder: "/images/uploads"        # Site içinde resimlerin ulaşım yolu

collections:
  - name: "blog_tr"
    label: "Blog Yazıları (Türkçe)"
    folder: "content/blog"
    create: true
    slug: "{{slug}}.tr"
    extension: "md"       # sadece md yazın
    format: "md"          # format da md
    fields:
      - { label: "Dil", name: "language", widget: "hidden", default: "tr" }
      - { label: "Başlık", name: "title", widget: "string" }
      - { label: "Tarih", name: "date", widget: "datetime" }
      - { label: "İçerik", name: "body", widget: "markdown" }

  - name: "blog_en"
    label: "Blog Posts (English)"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "md"  
    fields:
      - { label: "Language", name: "language", widget: "hidden", default: "en" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

