backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog Yazıları"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    extension: "md"
    fields:
      - { label: "Başlık", name: "title", widget: "string" }
      - { label: "Tarih", name: "date", widget: "datetime" }
      - { label: "Dil", name: "lang", widget: "select", options: ["tr", "en"], default: "tr" }
      - { label: "İçerik", name: "body", widget: "markdown" }
    meta: { path: { widget: "string", label: "Yol", name: "path" } }
    path: "{{slug}}{{#if (eq lang 'tr')}}.tr{{/if}}.md"
